language: python

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PIP_INSTALL='pip install'
    matrix:
        - SETUP_CMD='egg_info'

matrix:
    include:
        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'
        
        # Generate docs in Python 2
        - python: 2.7
          env: SETUP_CMD='build_docs'
        
        # Do a coverage test in Python 3.
        - python: 3.6
          env: SETUP_CMD='test --coverage'
          
        # Generate docs in Python 3
        - python: 3.6
          env: SETUP_CMD='build_docs'

before_install:

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

    # UPDATE APT-GET LISTINGS
    - sudo apt-get update
    
    # Choose environment file on the basis of python version
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then ENV_FILE=starkit_env27.yml;
      elif [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then ENV_FILE=starkit_env3.yml; fi

install:

    # CONDA
    - curl -O https://raw.githubusercontent.com/starkit/starkit/master/$ENV_FILE  # Download env file from starkit repo
    - conda env create -n starkit --file ./$ENV_FILE
    - source activate starkit
    # Install starkit since it is required by wsynphot 
    - pip install git+https://github.com/starkit/starkit

    # OPTIONAL DEPENDENCIES
    # Here you can add any dependencies your package may have. You can use
    # conda for packages available through conda, or pip for any other
    # packages. You should leave the `numpy=$NUMPY_VERSION` in the `conda`
    # install since this ensures Numpy does not get automatically upgraded.
    # - if [[ $SETUP_CMD != egg_info ]]; then $CONDA_INSTALL numpy=$NUMPY_VERSION ... ; fi
    # - if [[ $SETUP_CMD != egg_info ]]; then $PIP_INSTALL ...; fi

    # COVERAGE DEPENDENCIES
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then $PIP_INSTALL coverage coveralls; fi

script:
   - python setup.py $SETUP_CMD
   #- if [[ $SETUP_CMD == 'build_docs' ]]; then source deploy_docs.sh; fi

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
# - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='packagename/tests/coveragerc'; fi
